x-cypress-service: &cypress-service
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - .:/app
    - /app/node_modules
  deploy:
    resources:
      limits:
        memory: 2G
      reservations:
        memory: 1G
  environment:
    - CI=true

services:
  cypressTests:
    <<: *cypress-service
    command: npx cypress run

  uiTests:
    <<: *cypress-service
    command: npx cypress run --expose grepTags=@ui

  apiTests:
    <<: *cypress-service
    command: npx cypress run --expose grepTags=@api

  webtablesTests:
    <<: *cypress-service
    command: npx cypress run --expose grepTags=@webTables
