x-cypress-service: &cypress-service
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - .:/app
    - /app/node_modules
  deploy:
    resources:
      limits:
        memory: 2G
      reservations:
        memory: 1G
  environment:
    - CI=true

services:
  cypress-tests:
    <<: *cypress-service
    command: npx cypress run

  ui-tests:
    <<: *cypress-service
    command: npx cypress run --expose grepTags=@ui

  api-tests:
    <<: *cypress-service
    command: npx cypress run --expose grepTags=@api

  webtables-tests:
    <<: *cypress-service
    command: npx cypress run --expose grepTags=@webTables
