name: Run CI
permissions:
  contents: read
on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
            
            - name: Setup Node.js
              uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
              with:
                  node-version: "22"
                  cache: "npm"

            - name: Install Dependencies
              run: npm install
            
            - name: Run Linter
              run: npm run lint
            
            - name: Format Code
              run: npm run format:check

            - name: Verify Cypress setup
              run: npx cypress verify

            - name: Run smoke tests
              uses: cypress-io/github-action@7ef72e250a9e564efb4ed4c2433971ada4cc38b4 # v6.10.4
              with:
                  browser: chrome
                  env: grepTags=@smoke
                  publish-summary: true
                  install: false
            
            

            
