name: Run CI
permissions:
  contents: read
on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
            
            - name: Setup Node.js
              uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
              with:
                  node-version: "22"
                  cache: "npm"

            - name: Install Dependencies
              run: npm install
            
            - name: Run Linter
              run: npm run lint
            
            - name: Format Code
              run: npm run format:check

            - name: Verify Cypress setup
              run: npx cypress verify

            - name: Run smoke tests
              uses: cypress-io/github-action@82482149c343a5dee155d22104111b9319f9dd45 # v7.1.6
              with:
                  browser: chrome
                  publish-summary: true
                  install: false
              env:
                  GREP_TAGS: "@smoke"
            
            

            
